modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/clock_hud/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "clock_hud"
version = "${version}"
displayName = "Clock HUD"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"
displayURL = "https://mrmelon54.com/minecraft/clock-hud"

[[dependencies.clock_hud]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.clock_hud]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clock_hud]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
