modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/MrMelon54/clock_hud/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "clock_hud"
version = "${version}"
displayName = "Clock HUD"
authors = "MrMelon54"
description = "Display a clock on the client"
logoFile = "/icon.png"

[[dependencies.clock_hud]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clock_hud]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clock_hud]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"
