modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/clock_hud/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "clock_hud"
version = "${version}"
displayName = "Clock HUD"
authors = "MrMelon54"
description = "${description}"
logoFile = "icon.png"
displayURL = "https://mrmelon54.com/minecraft/clock-hud"

[[mixins]]
config="clock_hud.mixins.json"

[[mixins]]
config="clock_hud-common.mixins.json"

[[dependencies.clock_hud]]
modId = "minecraft"
type = "required"
versionRange = "${compatible_minecraft_versions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.clock_hud]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clock_hud]]
modId = "cloth_config"
type = "required"
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
