name: Java CI

on: [ push ]

jobs:
  resolve-versions:
    name: "Resolve Versions"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jo
      - id: set-matrix
        run: ./resolveversions.sh >> $GITHUB_OUTPUT

  build:
    needs: resolve-versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.resolve-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Create cache for builds
        uses: actions/cache@v4
        with:
          path: buildAllJars
          key: buildAllJars-key
      - name: Build
        run: ./buildsingle.sh "${{ matrix.mc }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached docker image
        uses: actions/cache/restore@v4
        with:
          path: buildAllJars
          key: buildAllJars-key
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          #!/bin/bash
          while read -r filename; do
            curl --fail -X POST -H "Authorization: Bearer ${{ secrets.DEPLOY }}" -F "upload=@$filename" https://api.mrmelon54.com/v1/mc-upload/upload/clock-hud
          done < <(find ./buildAllJars/ -name '*.jar' -type f)
